"""Add Menu and Food tables with ingredients and embedding

Revision ID: 6b83126b7be6
Revises: 
Create Date: 2025-05-05 13:48:34.705440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b83126b7be6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_image_url', sa.String(), nullable=True, comment='업로드된 원본 메뉴 이미지 URL'),
    sa.Column('ocr_text', sa.Text(), nullable=True, comment='OCR로 추출된 텍스트'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성 타임스탬프'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False, comment='이 음식이 속한 메뉴의 ID (외래 키)'),
    sa.Column('name', sa.String(), nullable=False, comment='음식 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='음식 설명'),
    sa.Column('image_url', sa.String(), nullable=True, comment='대표 음식 이미지 URL'),
    sa.Column('calories', sa.Float(), nullable=True, comment='칼로리 (kcal)'),
    sa.Column('protein', sa.Float(), nullable=True, comment='단백질 (g)'),
    sa.Column('carbs', sa.Float(), nullable=True, comment='탄수화물 (g)'),
    sa.Column('fat', sa.Float(), nullable=True, comment='지방 (g)'),
    sa.Column('allergens', sa.String(), nullable=True, comment='알레르기 유발 물질 정보'),
    sa.Column('translated_name', sa.String(), nullable=True, comment='번역된 음식 이름'),
    sa.Column('translated_description', sa.Text(), nullable=True, comment='번역된 음식 설명'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
