"""Add ingredients and embedding columns to Food table

Revision ID: d5850ecc7d7a
Revises: 6b83126b7be6
Create Date: 2025-05-05 21:04:26.664380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'd5850ecc7d7a'
down_revision: Union[str, None] = '6b83126b7be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('ingredients', sa.Text(), nullable=True, comment='주요 재료 목록 (쉼표 구분 또는 JSON 문자열)'))
    op.add_column('foods', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='음식 이름+재료 임베딩 벡터 (pgvector, 768차원 예시)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('foods', 'embedding')
    op.drop_column('foods', 'ingredients')
    # ### end Alembic commands ###
